const colors = {
  light: {
    text: "#0A0A10",
    tint: "#7C3AED",
    background: "#F5F5FA",
    foreground: "#0A0A10",
    card: "#FFFFFF",
    cardForeground: "#0A0A10",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EEEEF5",
    secondaryForeground: "#1A1A2E",
    muted: "#EEEEF5",
    mutedForeground: "#6B6B80",
    accent: "#7C3AED",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E2EC",
    input: "#E2E2EC",
    appreciate: "#22C55E",
    disagree: "#EF4444",
    publicMode: "#7C3AED",
    pseudonymousMode: "#F59E0B",
    anonymousMode: "#A855F7",
    gold: "#F59E0B",
    surface: "#FFFFFF",
  },
  dark: {
    text: "#EDEDF5",
    tint: "#A78BFA",
    background: "#09090E",
    foreground: "#EDEDF5",
    card: "#131318",
    cardForeground: "#EDEDF5",
    primary: "#A78BFA",
    primaryForeground: "#09090E",
    secondary: "#1C1C25",
    secondaryForeground: "#EDEDF5",
    muted: "#1C1C25",
    mutedForeground: "#7A7A90",
    accent: "#A78BFA",
    accentForeground: "#09090E",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1F1F2C",
    input: "#1F1F2C",
    appreciate: "#22C55E",
    disagree: "#EF4444",
    publicMode: "#A78BFA",
    pseudonymousMode: "#FBBF24",
    anonymousMode: "#C084FC",
    gold: "#FBBF24",
    surface: "#131318",
  },
  radius: 12,
};

export default colors;
